#TCC

###Importando bibliotecas

In [33]:
import string

import pandas as pd
import numpy as np
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from rake_nltk import Rake
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from unidecode import unidecode

In [8]:
# Flag para ativar o pre-processamento
aply_pre_process = True

In [10]:
def pre_process(corpus, stop_words_remv = True, lemmatizetion = True, stemmization = True):
    corpus = corpus.lower()
    stopset = None
    if (stop_words_remv):
        stopset = stopwords.words('english')
        stopset += list(string.punctuation)

    if (lemmatizetion):
        lemmatizer = WordNetLemmatizer()
        corpus = " ".join([lemmatizer.lemmatize(i) for i in word_tokenize(corpus) if i not in stopset])
    
    if (stemmization):
        stemmer = PorterStemmer()
        corpus = " ".join([stemmer.stem(i) for i in word_tokenize(corpus)])
    
    # remove non-ascii characters
    corpus = unidecode(corpus)
    
    return corpus

In [11]:
pd.set_option('display.max_columns', 100)
df = pd.read_csv('./IMDB_Top250Movies.csv')
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,1,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,English,USA,Nominated for 7 Oscars. Another 19 wins & 30 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.3/10,80.0,9.3,"1,825,626",tt0111161,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,2,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,"English, Italian, Latin",USA,Won 3 Oscars. Another 23 wins & 27 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.2/10,100.0,9.2,"1,243,444",tt0068646,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,3,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,"English, Italian, Spanish, Latin, Sicilian",USA,Won 6 Oscars. Another 10 wins & 20 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,85.0,9.0,"856,870",tt0071562,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,4,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,"English, Mandarin","USA, UK",Won 2 Oscars. Another 151 wins & 153 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,82.0,9.0,"1,802,351",tt0468569,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,5,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,English,USA,Nominated for 3 Oscars. Another 16 wins & 8 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.9/10,96.0,8.9,"494,215",tt0050083,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

In [12]:
df.shape

(250, 38)

In [13]:
df = df[['Title','Genre','Director','Actors','Plot']]
#df = df[['Title','Plot']]
df.head()

,Title,Genre,Director,Actors,Plot
0,The Shawshank Redemption,"Crime, Drama",Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...
2,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...
3,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...

In [14]:
df.shape

(250, 5)

In [32]:
amostra = df.sample(20)
amostra.to_csv('amostra.csv')

In [15]:
# descartando as vírgulas entre os nomes completos dos atores e obtendo apenas os três primeiros nomes
df['Actors'] = df['Actors'].map(lambda x: x.split(',')[:3])

# colocando os gêneros em uma lista de palavras
df['Genre'] = df['Genre'].map(lambda x: x.lower().split(','))

df['Director'] = df['Director'].map(lambda x: x.split(' '))

Mesclar o nome e o sobrenome de cada ator e diretor, por isso é considerado como uma palavra e não há mistura entre pessoas que compartilham um primeiro nome

In [16]:
for index, row in df.iterrows():
    row['Actors'] = [x.lower().replace(' ','') for x in row['Actors']]
    row['Director'] = ''.join(row['Director']).lower()

In [17]:
if (aply_pre_process):
    for index, row in df.iterrows():
        plot = row['Plot']
        row['Plot'] = pre_process(plot)

In [18]:
# iniciando uma nova coluna
df['Key_words'] = ""

In [19]:
for index, row in df.iterrows():
    plot = row['Plot']
    
    # instanciando Rake, por padrão usa palavras irrelevantes em inglês do NLTK 
    # e descarta todos os caracteres de pontuação
    r = Rake()

    # extraindo as palavras passando o texto
    r.extract_keywords_from_text(plot)

    # obtendo o dicionário com palavras-chave e suas pontuações
    key_words_dict_scores = r.get_word_degrees()
    
    # atribuindo as palavras-chave à nova coluna
    row['Key_words'] = list(key_words_dict_scores.keys())

In [20]:
# descartando a coluna Plot
df.drop(columns = ['Plot'], inplace = True)

df.set_index('Title', inplace = True)
df.head()

,Genre,Director,Actors,Key_words
Title,,,,
The Shawshank Redemption,"[crime, drama]",frankdarabont,"[timrobbins, morganfreeman, bobgunton]","[two, imprison, men, bond, number, year, find,..."
The Godfather,"[crime, drama]",francisfordcoppola,"[marlonbrando, alpacino, jamescaan]","[age, patriarch, organ, crime, dynasti, transf..."
The Godfather: Part II,"[crime, drama]",francisfordcoppola,"[alpacino, robertduvall, dianekeaton]","[earli, life, career, vito, corleon, 1920, new..."
The Dark Knight,"[action, crime, drama]",christophernolan,"[christianbale, heathledger, aaroneckhart]","[menac, known, joker, emerg, mysteri, past, wr..."
12 Angry Men,"[crime, drama]",sidneylumet,"[martinbalsam, johnfiedler, leej.cobb]","[juri, holdout, attempt, prevent, miscarriag, ..."

In [21]:
df['bag_of_words'] = ''
columns = df.columns
for index, row in df.iterrows():
    words = ''
    for col in columns:
        if col != 'Director':
            words = words + ' '.join(row[col])+ ' '
        else:
            words = words + row[col]+ ' '
    row['bag_of_words'] = words
    
df.drop(columns = [col for col in df.columns if col!= 'bag_of_words'], inplace = True)

df.head()

                                                               bag_of_words
Title
The Shawshank Redemption  crime  drama frankdarabont timrobbins morganfr...
The Godfather             crime  drama francisfordcoppola marlonbrando a...
The Godfather: Part II    crime  drama francisfordcoppola alpacino rober...
The Dark Knight           action  crime  drama christophernolan christia...
12 Angry Men              crime  drama sidneylumet martinbalsam johnfied...

In [23]:
# instanciando e gerando a matriz de contagem
count = CountVectorizer()
count_matrix = count.fit_transform(df['bag_of_words'])

In [46]:
count_matrix

<250x2660 sparse matrix of type '<class 'numpy.int64'>'
	with 5331 stored elements in Compressed Sparse Row format>

In [24]:
# criando uma Série para os títulos dos filmes para que sejam associados a uma 
# lista numérica ordenada que usarei posteriormente para corresponder aos índices
indices = pd.Series(df.index)
indices[:5]

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [32]:
df.index

Index(['The Shawshank Redemption', 'The Godfather', 'The Godfather: Part II',
       'The Dark Knight', '12 Angry Men', 'Schindler's List',
       'The Lord of the Rings: The Return of the King', 'Pulp Fiction',
       'Fight Club', 'The Lord of the Rings: The Fellowship of the Ring',
       ...
       'Deadpool', 'The Wild Bunch', 'Aladdin', 'Big Fish', 'Patton',
       'The Lost Weekend', 'Short Term 12', 'His Girl Friday',
       'The Straight Story', 'Slumdog Millionaire'],
      dtype='object', name='Title', length=250)

In [25]:
# gerando a matriz de similaridade de cosseno
cosine_sim = cosine_similarity(count_matrix, count_matrix)
cosine_sim

array([[1.        , 0.15789474, 0.13764944, ..., 0.05263158, 0.05263158,
        0.05564149],
       [0.15789474, 1.        , 0.36706517, ..., 0.05263158, 0.05263158,
        0.05564149],
       [0.13764944, 0.36706517, 1.        , ..., 0.04588315, 0.04588315,
        0.04850713],
       ...,
       [0.05263158, 0.05263158, 0.04588315, ..., 1.        , 0.05263158,
        0.05564149],
       [0.05263158, 0.05263158, 0.04588315, ..., 0.05263158, 1.        ,
        0.05564149],
       [0.05564149, 0.05564149, 0.04850713, ..., 0.05564149, 0.05564149,
        1.        ]])

In [30]:
# função que recebe o título do filme como entrada e retorna os 10 principais filmes recomendados
def recommendations(title, cosine_sim = cosine_sim):
    
    recommended_movies = []
    
    # obtendo o índice do filme que corresponde ao título
    idx = indices[indices == title].index[0]

    # criando uma série com as pontuações de similaridade em ordem decrescente
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    print(score_series)
    # obtendo os índices dos 10 filmes mais parecidos
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    # preenchendo a lista com os títulos dos 10 melhores filmes correspondentes
    for i in top_10_indexes:
        recommended_movies.append(list(df.index)[i])
        
    return recommended_movies

In [31]:

recommendations('Fargo')

128    1.000000
226    0.259259
132    0.230940
34     0.226805
1      0.220755
         ...
150    0.000000
217    0.000000
145    0.000000
219    0.000000
82     0.000000
Length: 250, dtype: float64

['Rope',
 'No Country for Old Men',
 'The Departed',
 'The Godfather',
 'Reservoir Dogs',
 'Baby Driver',
 'The Godfather: Part II',
 'The Wolf of Wall Street',
 'On the Waterfront',
 'Goodfellas']

In [30]:
def recommender_10_more_frequenly(movies, cosine_sim = cosine_sim):
    more_frequent = {}
    # Para cada filme recebido pegar as recomendações dele e colocar em um dicionário com uma contagem
    for movie in movies:
        recommended_movies = recommendations(movie, cosine_sim)
        for i in recommended_movies:
            if i not in more_frequent:
                more_frequent[i] = 1
            else:
                more_frequent[i] += 1
    
    # cria um dicionário ordenado de forma crescente com os filmes mais recomendados
    more_frequent = dict(sorted(more_frequent.items(), key=lambda item: item[1], reverse=True))

    # remover do dicionário os filmes passados na lista
    for movie in movies:
        if movie in more_frequent:
            del more_frequent[movie]

    #Pega os 10 mais frequentes
    ten_more_flequent_name = list(more_frequent.keys())[:10]

    return ten_more_flequent_name

In [31]:
movies = ['Interstellar',
 'Gladiator',
 '2001: A Space Odyssey',
 'Star Wars: The Force Awakens',
 'Catch Me If You Can',
 'Baby Driver',
 'The Godfather: Part II',
 'The Wolf of Wall Street',
 'On the Waterfront',
 'Goodfellas']

test = recommender_10_more_frequenly(movies)
test

['The Godfather',
 'Touch of Evil',
 'Fargo',
 'The Martian',
 'The Departed',
 'Heat',
 'Rope',
 'Cool Hand Luke',
 'Aliens',
 'Chinatown']

In [55]:

def get_similarity(interacted_items, cosine_similarity = cosine_sim):
        
    # obtendo os índices dos filmes interagidos
    idcs_interact = []
    for item in interacted_items:
        idcs_interact.append(indices[indices == item].index[0])

    similarity_non_interacted_items = []

    # obtendo os índices dos filmes não interagidos
    idcs_not_interact = [idc for idc in list(indices.index) if idc not in idcs_interact]

    # pegando lista de similaridades dos itens não interagidos
    for idc in idcs_not_interact:
        similarity_non_interacted_items.append(cosine_similarity[idc])

    # zerando a similaridade dos itens interagidos nas listas de similaridade dos itens não interagidos
    for similarity_item in similarity_non_interacted_items:
        for index in idcs_interact:
            similarity_item[index] = 0.0

    # obtendo a similaridade média
    num_of_items = len(similarity_non_interacted_items[0])
    sum_similarity = np.array([0.0] * num_of_items)
    for similarity_item in similarity_non_interacted_items:
        sum_similarity += np.array(similarity_item)

    average_similarity = sum_similarity / num_of_items

    items_more_similar = pd.Series(average_similarity).sort_values(ascending = False)

    # pegando o top 10 indices de filmes mais similares
    top_10_indexes = list(items_more_similar.iloc[0:10].index)

    recommended_movies = []
    
    # preenchendo a lista com os títulos dos 10 melhores filmes correspondentes
    for i in top_10_indexes:
        recommended_movies.append(list(df.index)[i])
        
    return recommended_movies

In [56]:
movies = ['Interstellar',
 'Gladiator',
 '2001: A Space Odyssey',
 'Star Wars: The Force Awakens',
 'Catch Me If You Can',
 'Baby Driver',
 'The Godfather: Part II',
 'The Wolf of Wall Street',
 'On the Waterfront',
 'Goodfellas']

movies_recomended = get_similarity(movies)
movies_recomended

98     0.074983
123    0.074549
226    0.072366
214    0.071789
93     0.070032
         ...
100    0.000000
15     0.000000
38     0.000000
2      0.000000
25     0.000000
Length: 250, dtype: float64

['The Gold Rush',
 'Cool Hand Luke',
 'Rope',
 'Arsenic and Old Lace',
 'Judgment at Nuremberg',
 'The Sting',
 'The Great Escape',
 'The Imitation Game',
 'Witness for the Prosecution',
 'The Green Mile']